### ISSUE TITLE
final_master_dataset.csv does not contain 1690 questions

### ISSUE THREAD

**Issue by ogencoglu** [JerryWei03/COVID-Q#1]
Thanks for the dataset. 

_final_master_dataset.csv_ does not seem to contain 1690 annotated questions as stated in your preprint. There are 1611 rows and only 1245 are annotated in terms of *Category*.

Any clarification would be appreciated.

**Comment by JerryWeiAI** [comment]
Hello

The 1,690 questions reported in our paper includes duplicated questions. When creating Table 1 (which reports the number of valid questions for each of our sources), we did not remove duplicate questions from the count because it cannot be determined which source was the duplicate. For example, if the same question is found in both Google and Bing, we cannot determine whether to subtract 1 from the Google count or from the Bing count. In this instance, because it is matters which source the duplicate question came from, we cannot simply delete the question.
However, when creating the usable final dataset, it does not matter which source we pick, as long as we include only one version of the question.

Thanks for bringing this up!
